### ISSUE TITLE
Put progressbar up on Maven repo?

### ISSUE THREAD

**Issue by Avec112** [raszi/java-progressbar#1]
Not an issue and more an request. 
I would love to see ProgressBar up on Maven Central repository :+1:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

**Comment by raszi** [comment]
Thanks for the tutorial, I'll do when I'll have spare time.

**Comment by milosimpson** [comment]
+1.   Would also be good to update the dependencies.

**Comment by raszi** [comment]
I've created an issue at Sonatype [here](https://issues.sonatype.org/browse/OSSRH-22447)

**Comment by raszi** [comment]
@milosimpson I've also updated the dependencies.

**Comment by milosimpson** [comment]
Cool.

**Comment by ramandeep89** [comment]
@milosimpson +1

**Comment by aldwyish** [comment]
👍

**Comment by lewismc** [comment]
@raszi any plans to publish this library?

**Comment by olskaw** [comment]
There is an alternative with https://jitpack.io. It allows you to add public github repos. Simple put this in your build.gradle file:

	buildscript {
		repositories {
			jcenter()
			maven { url 'https://jitpack.io' }
		}
	}

	dependencies {
		...
		compile 'com.github.raszi:java-progressbar:-SNAPSHOT'
		...
	}

Unfortunately it does not work with the current master snapshot. I guess this due to the build fails. Have a look on https://github.com/raszi/java-progressbar/issues/7. This is very simple to fix it.

**Comment by raszi** [comment]
Fixed by #10
